Automech/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings  
from django.conf.urls.static import static 
from client.views import CustomSignupView
urlpatterns = [
    path('admin/', admin.site.urls),
    path('customadmin/',include('client.admin_urls')),
    path('manager/',include('client.manager_urls')),
    path('mechanic/',include('client.mech_urls')),
    path('cart/',include('client.cart_urls')),
    path ('',include('client.urls')),
    path('accounts/',include('allauth.urls')),
    path ('account/ signup/', CustomSignupView.as_view(), name='account_signup'),
    path('tinymce/', include('tinymce.urls')),
   
]
if settings.DEBUG:  
        urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)  

client/urls.py
from .import views
from django.urls import  path
from django.contrib.auth import views as auth_views
from .views import CustomSignupView 

urlpatterns = [
path('',views.index,name="index"),
path('account/profile/',views.profileview,name="account_profile"),
path('account/profilesetup/',views.profilesetup,name="profile_setup"),
path('step1/',views.step1_view, name='step1_view'),
path('step2/', views.step2_view, name='step2_view'),
path('step3/',views.step3_view,name="step3_view"),
path('vehicle/',views.vehicle,name="vehicle"),
path('vehicle/add',views.add_vehicle,name="vehicle_add"),
path('vehicle/edit/<int:id>/', views.edit_vehicle, name='vehicle_edit'),
path('get_car_models/<int:make_id>/', views.get_car_models, name='get_car_models'),
path('get_model_variants/', views.get_model_variants, name='get_model_variants'),
path('get_models/', views.get_models, name='get_models'),
path('u_vehicle',views.uservehicle,name='uservehicle'),
path('map/', views.map_view, name='map_view'),
path('get_category_data/<slug:category_slug>/', views.get_category_data, name='get_category_data'),
path('service/cost',views.servicecost_estimation,name='service_cost_finder'),

# RSA URLS
path('rsa/request',views.rsa,name='rsarequest'),
path('rsa/details',views.rsadetails,name='rsadetails'),

path('blog/',views.client_blog,name='client_blog'),
path('blog/<slug:blog_slug>/',views.client_blog_details,name='client_blog_details'),

path('like_post/<slug:post_slug>/',views.like_post, name='like_post'),
path('Terms',views.terms,name='terms'),
path('Privacy',views.privacy,name='privacy'),

path('Vehicles',views.vehicel_details,name='my_vehicles'),
path('logout/', views.custom_logout, name='custom_logout'),
path('cars/',views.car,name='cars'),
path('Vehicles/History/<str:vehicle_Regno>',views.service_history,name='history'),
#for vehicle select
path('load_car_make/', views.load_car_make, name='load_car_make'),
path('load_car_models/<int:make_id>/', views.load_car_models, name='load_car_models'),
path('load_model_variants/<int:model_id>/', views.load_model_variants, name='load_model_variants'),
path('setcar/<slug:var_slug>', views.setcar, name='setcar'),
path('check_vehicle_exists/', views.check_vehicle_exists, name='check_vehicle_exists'),
path('warning-alarm/',views.warning_alarm, name='warning_alarm'),
path('check_email_exists/', views.check_email_exists, name='check_email_exists'),
path('tables/',views.tablepage,name="tables"),
]

client/models.py
from django.db import models
from django.utils.text import slugify
from django.contrib.auth.models import AbstractUser,BaseUserManager
from django.utils import timezone

class CustomUserManager(BaseUserManager):
    def create_superuser(self, email, first_name, last_name, password=None, **extra_fields):
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)

        return self.create_user(email, first_name, last_name, password, **extra_fields)
    def create_user(self, email, first_name, last_name, password=None, **extra_fields):
        if not email:
            raise ValueError('The Email field must be set')
        email = self.normalize_email(email)
        user = self.model(email=email, first_name=first_name, last_name=last_name, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

class User(AbstractUser):
    
    email=models.EmailField(max_length=100,unique=True)
    USERNAME_FIELD='email'
    REQUIRED_FIELDS=['first_name', 'last_name']
    class Role(models.TextChoices):
        ADMIN="ADMIN",'Admin'
        MECHANIC="MECHANIC",'Mechanic'
        MANAGER="MANAGER",'Manager'
        CLIENT="CLIENT",'Client'
    slug = models.SlugField(unique=True,blank=True)
    base_role = Role.CLIENT

    role = models.CharField(max_length=50, choices=Role.choices)
    objects = CustomUserManager()

    def save(self, *args, **kwargs):
        if not self.pk:
            self.role = self.base_role

        if not self.slug:
            base_slug = slugify(self.first_name)  
            unique_slug = base_slug
            counter = 1
            while User.objects.filter(slug=unique_slug).exists():
                unique_slug = f"{base_slug}-{counter}"
                counter += 1
            self.slug = unique_slug

        return super().save(*args, **kwargs)

class Client(User):

    base_role = User.Role.CLIENT
    class Meta:
        proxy = True

class Mechanic(User):

    base_role = User.Role.MECHANIC
    
    class Meta:
        proxy = True

class Manager(User):

    base_role = User.Role.MANAGER
    
    class Meta:
        proxy = True

class UserInfo(models.Model):
    client = models.OneToOneField(Client, on_delete=models.CASCADE)
    contact_no = models.CharField(max_length=11)
    address=models.CharField(max_length=100,null=True)
    place = models.CharField(max_length=100)
    city = models.CharField(max_length=100)
    district = models.CharField(max_length=100)
    pincode = models.CharField(max_length=6)
    profile_picture = models.ImageField(upload_to='profile_pictures/', blank=True, null=True)


class CarMake(models.Model):
    make_name = models.CharField(max_length=100,unique=True)
    make_Image = models.ImageField(upload_to='make_images/',blank=True, null=True)
    make_slug = models.SlugField(max_length=100, unique=True, blank=True, null=True)

    def save(self, *args, **kwargs):
        self.make_slug = slugify(self.make_name)
        super().save(*args, **kwargs)

    def __str__(self):
        return self.make_name

class CarModel(models.Model):
    model_name = models.CharField(max_length=100,unique=True)
    make_company = models.ForeignKey(CarMake, on_delete=models.CASCADE)
    model_Image = models.ImageField(upload_to='model_images/',blank=True, null=True)
    model_slug = models.SlugField(max_length=100, unique=True, blank=True, null=True)

    def save(self, *args, **kwargs):
        self.model_slug = slugify(self.model_name)
        super().save(*args, **kwargs)

    def __str__(self):
        return self.model_name

class Fueltype(models.Model):
    fuel_name = models.CharField(max_length=50,unique=True)
    def __str__(self):
        return self.fuel_name

class transmissionType(models.Model):
    transmission_name = models.CharField(max_length=50,unique=True)
    def __str__(self):
        return self.transmission_name

class ModelVariant(models.Model):
    model = models.ForeignKey(CarModel, on_delete=models.CASCADE)
    fuel_type = models.ForeignKey(Fueltype, on_delete=models.CASCADE)
    torque = models.CharField(max_length=50)
    bhp = models.CharField(max_length=50)
    engine = models.CharField(max_length=50)
    transmission = models.ForeignKey( transmissionType , on_delete=models.CASCADE)
    tyre_size = models.CharField(max_length=50)
    variant_name = models.CharField(max_length=50)
    variant_slug = models.SlugField(max_length=100, unique=True, blank=True, null=True)

    def save(self, *args, **kwargs):
        self.variant_slug = slugify(f"{self.model.model_name}-{self.variant_name}")
        super().save(*args, **kwargs)


    def __str__(self):
        return f"{self.model.model_name} - {self.variant_name}"
    class Meta:
        unique_together = ('model', 'variant_name',)



class Vehicleinfo(models.Model):
    client = models.ForeignKey(User, on_delete=models.CASCADE)
    model_variant = models.ForeignKey(ModelVariant, on_delete=models.CASCADE)
    vehicle_Regno = models.CharField(max_length=20, unique=True)

class ServiceCategory(models.Model):
    category_name = models.CharField(max_length=100,unique=True)
    slug = models.SlugField(unique=True, blank=True)
    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.category_name)
        super().save(*args, **kwargs)

    def __str__(self):
        return self.category_name

class Task(models.Model):
    task_name = models.CharField(max_length=255)
    slug = models.SlugField(unique=True, blank=True)

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.task_name)
        super().save(*args, **kwargs)

    def __str__(self):
        return self.task_name

class ServiceList(models.Model):
    service_name = models.CharField(max_length=255,unique=True)
    service_category = models.ForeignKey('ServiceCategory', on_delete=models.CASCADE)
    description = models.TextField(null=True, blank=True)
    service_Image = models.ImageField(upload_to='service_images/',blank=True, null=True)
    tasks = models.ManyToManyField(Task)
    slug = models.SlugField(unique=True, blank=True)
    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.service_name )
        super().save(*args, **kwargs)
        
    def __str__(self):
        return self.service_name
    
class ServiceCenter(models.Model):
    place = models.CharField(max_length=100)
    city = models.CharField(max_length=50)
    pincode = models.CharField(max_length=6)
    phone_number = models.CharField(max_length=15)
    latitude = models.DecimalField(max_digits=9, decimal_places=6)
    longitude = models.DecimalField(max_digits=9, decimal_places=6)
    manager = models.OneToOneField(Manager, on_delete=models.SET_NULL, null=True, blank=True, unique=True)
    slug = models.SlugField(unique=True, blank=True)

    def save(self, *args, **kwargs):
        if not self.slug:
            base_slug = slugify(f"{self.place}-{self.city}")
            unique_slug = base_slug
            counter = 1
            while ServiceCenter.objects.filter(slug=unique_slug).exists():
                unique_slug = f"{base_slug}-{counter}"
                counter += 1
            self.slug = unique_slug

        super().save(*args, **kwargs)
    
    def __str__(self):
        return self.place
    

class mechanicList(models.Model):
    mechanic = models.OneToOneField(Client, on_delete=models.CASCADE)
    service_center = models.ForeignKey(ServiceCenter, on_delete=models.CASCADE)

    def __str__(self):
        return str(self.mechanic)
   
class ServicesSlots(models.Model):
    slotname = models.CharField(max_length=100)
    service_center = models.ForeignKey(ServiceCenter, on_delete=models.CASCADE)
    allocated_mech = models.ForeignKey(Client, on_delete=models.CASCADE, null=True, blank=True)  # Assuming Client is the correct model for the mechanic
    STATUS_CHOICES = [('ACTIVE','Active'),('INACTIVE','Inactive')]
    status = models.CharField(max_length=50, choices=STATUS_CHOICES, default='INACTIVE')
    slug = models.SlugField(unique=True, blank=True)

    def save(self, *args, **kwargs):
        if not self.slug:
            base_slug = slugify(self.slotname)
            unique_slug = base_slug
            counter = 1
            while ServicesSlots.objects.filter(slug=unique_slug).exists():
                unique_slug = f"{base_slug}-{counter}"
                counter += 1
            self.slug = unique_slug
        super().save(*args, **kwargs)

    def __str__(self):
        return f"{self.slotname} - {self.service_center.place} - {self.allocated_mech.get_full_name()} - {self.status}"
    


class ServicePrice(models.Model):
    variant = models.ForeignKey(ModelVariant, on_delete=models.CASCADE)
    service = models.ForeignKey(ServiceList, on_delete=models.CASCADE)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    slug = models.SlugField(unique=True, max_length=255, editable=False)

    def save(self, *args, **kwargs):
        if not self.id:
            self.slug = slugify(f"{self.variant.model}-{self.variant.variant_name}-{self.service.service_name}")
        super().save(*args, **kwargs)

    def __str__(self):
        return f"{self.variant.variant_name} - {self.service.service_name}"

    class Meta:
        unique_together = ('variant', 'service',)


import uuid
class Cart(models.Model):
    client = models.ForeignKey(User, on_delete=models.CASCADE)
    vehicle_info = models.ForeignKey(Vehicleinfo, on_delete=models.CASCADE)
    service_list = models.ForeignKey(ServiceList, on_delete=models.CASCADE)
    slug = models.SlugField(unique=True, blank=True)

    class Meta:
        unique_together = ['client', 'vehicle_info', 'service_list']

    def save(self, *args, **kwargs):
        if not self.slug:
            unique_id = uuid.uuid4().hex[:10]

templates/client/index.html
{% extends 'client/base.html' %}
{%block content%}
{% load static %}
    {%if is_filled%}
<div class="alert alert-warning alert-dismissible fade show" role="alert">
    <strong>{{user.name}}</strong> You should check in on some of those fields below.
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
{% endif %}

<script>
  // Check if a flag is set in the sessionStorage to ensure it's executed only once
  if (!sessionStorage.getItem('pageReloaded')) {
      // Set the flag in sessionStorage to prevent further reloads
      sessionStorage.setItem('pageReloaded', 'true');

      // Reload the page after a short delay (adjust the delay as needed)
      setTimeout(function() {
          window.location.reload();

          // Clear the session history to prevent going back
          window.history.forward();
      }, 1000);  // Adjust the delay before the initial reload
  }
</script>
 <!-- Carousel Start -->
 <div class="carousel">
<div class="container-fluid">
      <div class="owl-carousel">
          <div class="carousel-item">
              <div class="carousel-img">
                  <img src="{% static 'img/carousel-1.jpg'%}" alt="Image">
              </div>
              <div class="carousel-text">
                  <h3>Your Car, Our Care</h3>
                  <h1>Keep your Car Newer</h1>
                  <p>
                    Where good service meets good value.
                  </p>
                  <a class="btn btn-custom" href="">Explore More</a>
              </div>
          </div>
          <div class="carousel-item">
              <div class="carousel-img">
                  <img src="{% static 'img/carousel-2.jpg'%}" alt="Image">
              </div>
              <div class="carousel-text">
                  <h3>Your Car, Our Care</h3>
                  <h1>Quality service for you</h1>
                  <p>
                    Where good service meets good value.
                  </p>
                  <a class="btn btn-custom" href="">Explore More</a>
              </div>
          </div>
          <div class="carousel-item">
              <div class="carousel-img">
                  <img src="{% static 'img/carousel-3.jpg'%}" alt="Image">
              </div>
              <div class="carousel-text">
                  <h3>Your Car, Our Care</h3>
                  <h1>Driving Excellence, Servicing Brilliance.</h1>
                  <p>
                    We Care for Your Car Like Our Own
                  </p>
                  <a class="btn btn-custom" href="">Explore More</a>
              </div>
          </div>
      </div>
  </div>
</div>
<!-- Carousel End -->
<div class="container mt-5">
  <div class="row">
    <div class="col text-right">
     {% comment %} <button type="button" class="btn btn-primary" onclick="openForm()">Click me</button> {% endcomment %}
    </div>
  </div>
</div>

{% comment %} Modal For Car Select {% endcomment %}
<div class="modal fade" id="exampleModalCenter" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered car-width-modal" role="document">
    <div class="modal-content">
      <div class="modal-body" id="mycar">

        {% comment %} {% include 'client/partials/user_vehicles.html' with vehicles=vehicleinfo%} {% endcomment %}
        {% include 'client/partials/car_make.html' with car_makes=makes %}
      </div>
    </div>
  </div>
</div>

<div class="single">
  <div class="container">
      <div class="section-header text-center">
          <h2>Choose Your Service</h2>
      </div>
      {% comment %} {% if request.session.selected_vehicle %}
        <p>Selected Vehicle ID: {{ request.session.selected_vehicle }}</p>
    {% else %}
        <p>No vehicle selected</p>
    {% endif %} {% endcomment %}
    <div class="row">
      <div class="col-lg-8">
        <div class="single-tags">
          {% for category in categories %}
            <a href=""
              data-category-slug="{{ category.slug }}"
              class="{% if request.resolver_match.url_name == 'get_category_data' and category.slug == request.GET.category_slug %}active{% endif %}"
              hx-get="{% url 'get_category_data' category_slug=category.slug %}"
              hx-trigger="{% if forloop.first %}load once{% else %}click{% endif %}"
              hx-target="#category-data">{{ category.category_name }}</a>
            {% endfor %}
        </div>
      </div>
      <div>
        <!--Details Of Selected Vehicle-->
        {% if carvariant %}
        {{carvariant}}
        <img src="{{carvariant.model.model_Image.url}}" width="100">
        <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModalCenter">
          change
        </button>
        {% else %}
          <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModalCenter">
            Select Car
          </button>
        {% endif %}    
      </div>
    </div>
  </div>
</div>
<div id="category-data">
    <!-- Data for the selected category will be loaded here -->
</div>


<script>
  $(document).ready(function () {
    // Function to update models dropdown based on the selected make
    function updateModelsDropdown() {
        var makeId = $('#id_make_company').val();
        if (makeId) {
            $.ajax({
                url: '/get_models/',
                data: {'make_id': makeId},
                dataType: 'json',
                success: function (data) {
                    var modelSelect = $('#id_model_name');
                    modelSelect.empty();
                    modelSelect.append('<option value="">---------</option>');
                    $.each(data.models, function (key, value) {
                        modelSelect.append('<option value="' + value.id + '">' + value.name + '</option>');
                    });

                    // Trigger change on model dropdown to update model variants
                    modelSelect.trigger('change');
                }
            });
        }
    }

    // Initial setup
    updateModelsDropdown();

    // Event handler for make dropdown change
    $('#id_make_company').change(function () {
        updateModelsDropdown();
    });

    // Event handler for model dropdown change
    $('#id_model_name').change(function () {
        var modelId = $(this).val();
        if (modelId) {
            $.ajax({
                url: '/get_model_variants/',
                data: {'model_id': modelId},
                dataType: 'json',
                success: function (data) {
                    var variantSelect = $('#id_model_variant');
                    variantSelect.empty();
                    variantSelect.append('<option value="">---------</option>');
                    $.each(data.variants, function (key, value) {
                        variantSelect.append('<option value="' + value.id + '">' + value.name + '</option>');
                    });
                }
            });
        }
    });
});
</script>
<!-- Price Start -->
</div>


<div class="price">
    <div class="container">
      <div class="row">
        <div class="section-header text-center">
            <p>What We Do?</p>
            <h2>We offer full service auto repair <br>& maintenance</h2>
        </div>
        <div class="container mt-4">
          <div class="row">
            <div class="col-md-4">
              <div class="image-container">
                <img  src="{% static 'img/wwd1.png' %}">
              </div>
            </div>
            <div class="col-md-4">
              <div class="image-container">
                <img class="img-fluid zoom-image" src="{% static 'img/wwd2.jpg' %}">
              </div>
            </div>
            <div class="col-md-4">
              <div class="image-container">
                <img src="{% static 'img/wwd3.png' %}">
              </div>
            </div>
          </div>
          <div class="row">
            <div class="col-md-4 ">
              <div class="image-container">
                <img class="img-fluid zoom-image" src="{% static 'img/wwd4.jpeg' %}">
              </div>
            </div>
            <div class="col-md-4">
              <div class="image-container">
                <img src="{% static 'img/wwd5.png' %}">
              </div>
            </div>
            <div class="col-md-4">
              <div class="image-container">
                <img class="img-fluid zoom-image" src="{% static 'img/wwd6.jpeg' %}">
              </div>
            </div>
          </div>
        </div>
    </div>
</div>

<!-- Price End -->

{%endblock%}

templates/client/servicecost_estimation.html
{% extends 'client/base.html' %}
{%block content%}
{% load static %}
    {%if is_filled%}
<div class="alert alert-warning alert-dismissible fade show" role="alert">
    <strong>{{user.name}}</strong> You should check in on some of those fields below.
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
{% endif %}

<!-- Price Start -->
<div class="price">
  <div class="container">
    <div class="row">
        <div class="container mt-4">
            <form method="post" action="" id="yourForm">
                {% csrf_token %}
                <div class="form-row">
                    <div class="form-group col-md-3">
                        <label for="id_make_company">Make Company:</label>
                        <select id="id_make_company" name="make_company" class="form-control" onchange="validateMakeCompany()">
                            <option value="">--Please choose an option--</option>
                            {% for make in make_companys %}
                                <option value="{{ make.id }}">{{ make }}</option>
                            {% endfor %}
                        </select>
                        <span id="makeCompanyError" class="text-danger"></span>
                    </div>
                    <div class="form-group col-md-3">
                        <label for="id_model_name">Model Name:</label>
                        <select id="id_model_name" name="model_name" class="form-control" required>
                            <option value="">--Please choose an option--</option>
                            {% for model_name in model_names %}
                                <option value="{{ model_name.id }}">{{ model_name }}</option>
                            {% endfor %}
                        </select>
                    </div>
                    <div class="form-group col-md-3">
                        <label for="id_model_variant">Vehicle</label>
                        <select id="id_model_variant" name="model_variant" class="form-control" onchange="validateModelVariant()" required>
                            <option value="">--Please choose an option--</option>
                            {% for model_variant in model_variants %}
                                <option value="{{ model_variant.id }}">{{ model_variant }}</option>
                            {% endfor %}
                        </select>
                        <span id="modelVariantError" class="text-danger"></span>
                    </div>
                    <div class="form-group col-md-3">
                        <input type="submit" class="btn btn-primary mt-4  p-3" value="Search" onclick="validateForm()">
                        <p id="validationMessage" class="text-danger"></p>
                    </div>
                </div>
            </form>
        </div>
    </div>
  </div>
</div>
<div class="price">
  <div class="container">
   {% if resvariant %}
    <div class="col">
        <div class="section-header text-left ml-3">
            <p>Service Price For</p>
            <h2> {{resvariant}}</h2>
        </div>
    </div>

    {%endif%}
              <div class="row">

                {% comment %} {% for service in services %}
                    <li>{{ service.service_name }}: {{ service.description }} - Price: {{ service.serviceprice_set.all.first.price }}</li>
                        {% empty %}
                            <li>No services available for this variant.</li>
                {% endfor %} {% endcomment %}
                {% comment %} {%for service_price in service_prices %}
                    <div class="col-md-3">
                        <div class="price-item featured-item">
                            <div class="image-model-container">
                                <div class="duration-container">
                                    4 Hrs Taken
                                </div>
                                <img src="{{ service_price.service.service_Image.url }}"  class="img-fluid zoom-modimage" alt="Your Image">
                            </div>
                            <div class="price-header">
                                <h3> {{service_price.service.service_name }}</h3>
                                {{service_price.service.description }}
                                <h2><span>₹ {{service_price.price}}</span></h2>
                            </div>
                            <div class="price-footer">
                                <a class="btn btn-custom" href="">Book Now</a>
                            </div>
                        </div>
                    </div>
                {%endfor%}     {% endcomment %}
                {%for service, price in services_with_prices %}
                    <div class="col-md-3 mb-2">
                        <div class="price-item featured-item d-flex flex-column h-100">
                            <div class="image-model-container">
                                <div class="duration-container">
                                    4 Hrs Taken
                                </div>
                                <img src="{{service.service_Image.url }}"  class="img-fluid zoom-modimage" alt="Your Image">
                            </div>
                            <div class="price-header">
                                <h3> {{service.service_name }}</h3>
                                {{service.description }}
                                <h2><span>₹ {{price.price }}</span></h2>
                                {% if price == 0%}
                                These service Unavailable
                                {%endif%}
                            </div>
                            {% comment %} <div class="price-footer mt-auto">
                                <a class="btn btn-custom" href="">Book Now</a>
                            </div> {% endcomment %}
                        </div>
                    </div>
                {%endfor%}                
                 
              </div>
      </div>
  </div>
</div>
<script>
$(document).ready(function () {
  function updateModelNames() {
      var makeId = $('#id_make_company').val();
      if (makeId) {
          $.ajax({
              url: '/get_models/',  // Replace with your actual URL
              data: {'make_id': makeId},
              dataType: 'json',
              success: function (data) {
                  var modelSelect = $('#id_model_name');
                  modelSelect.empty();
                  modelSelect.append('<option value="">---------</option>');
                  $.each(data.models, function (key, value) {
                      modelSelect.append('<option value="' + value.id + '">' + value.name + '</option>');
                  });
                  updateModelVariants();  // Update model variants as well
              }
          });
      } else {
          // Reset model and variant dropdowns if make is not selected
          $('#id_model_name').empty();
          $('#id_model_variant').empty();
      }
  }

  function updateModelVariants() {
      var modelId = $('#id_model_name').val();
      if (modelId) {
          $.ajax({
              url: '/get_model_variants/',  // Replace with your actual URL
              data: {'model_id': modelId},
              dataType: 'json',
              success: function (data) {
                  var variantSelect = $('#id_model_variant');
                  variantSelect.empty();
                  variantSelect.append('<option value="">---------</option>');
                  $.each(data.variants, function (key, value) {
                      variantSelect.append('<option value="' + value.id + '">' + value.name + '</option>');
                  });
              }
          });
      } else {
          // Reset variant dropdown if model is not selected
          $('#id_model_variant').empty();
      }
  }

  // Initial setup
  updateModelNames();

  // Event handlers
  $('#id_make_company').change(function () {
      updateModelNames();
  });

  $('#id_model_name').change(function () {
      updateModelVariants();
  });
});

</script>
{%endblock%}